// src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { AgGridModule } from 'ag-grid-angular';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, AgGridModule],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'portfolio';
}

<section>
  <div class="introHeader">
    <h1 id="name">Tyler Arista</h1>
    <h3 id="bio">CS Student &#64;Calvin University</h3>
    <p id="bioDescription">I build accessible, pixel-perfect digital experiences for the web</p>
  </div>
  <app-navbar id="navbar"></app-navbar>
  <footer class="social-media">
    <a href="https://github.com/tarista13">
      <i class="bi bi-github"></i>
    </a>
    <a href="https://www.linkedin.com/in/tyler-arista/">
      <i class="bi bi-linkedin"></i>
    </a>
    <a href="https://www.instagram.com/t_arista13/">
      <i class="bi bi-instagram"></i>
    </a>
    <a href="https://twitter.com/t_arista13">
      <i class="bi bi-twitter-x"></i>
    </a>
  </footer>
</section>
<aside>
  <div class="about">
    <p>Currently pursuing a Computer Science degree with a minor in Data Science at Calvin University, I am deeply passionate about evolving into a skilled software engineer/software development. My coursework has encompassed crucial subjects including Data Structures, Algorithms, Software Engineering, Computer Architecture, Artificial Intelligence, and Machine Learning. With a fervent interest in technology and a solid foundation in key areas of computer science, I aim to leverage these skills to contribute meaningfully in the field of software development.</p>
    <p>Skills: Python, C#, JavaScript, ASP.NET MVC, Angular, ReactNative, Git, SQL, Agile Methodologies</p>
    <p>Interests: Software Engineering, ...</p>
  </div>
  <div class="education">
    <app-education
    [schoolName]="'Calvin University'"
    [major]="'Computer Science'"
    [minor]="'Data Science'"
    [graduationDate]="'May 2025'"
    [location]="'Grand Rapids, MI'"
    [relatedCourses]="'Introduction to Computing, Introduction to Data Structures, Data Structures & Algorithms, Computer Language Concepts, Software Engineering, Artificial Intelligence, Machine Learning ,Introduction to Computer Architecture, Operating Systems & Networking, Web Development(Fall 2024), Linear Algebra, Discrete Mathematics for Computing, Discrete Mathematics, Statistics, Calculus 1'"
    [imageSrc]="'../../../assets/calvinLogo.png'">
    </app-education>
  </div>
  <div class="experience">
    <app-job-card
    [jobTitle]="'Software Engineer Intern'"
    [companyName]="'Steelcase'"
    [location]="'Grand Rapids, MI'"
    [startDate]="'May 2024'"
    [endDate]="'Present'"
    [jobDescription]="'Collaborated on developing a new quoting application for customized products, improving frontend user experience and backend data management to streamline orders, while also creating an interactive dashboard to track usage and performance metrics of a generative AI space design tool by integrating the API with the database. Additionally, updated the Event Viewer to enhance functionality.'">
    </app-job-card>
    <app-job-card
    [jobTitle]="'CyberSecurity Intern'"
    [companyName]="'Steelcase'"
    [location]="'Grand Rapids, MI'"
    [startDate]="'May 2023'"
    [endDate]="'Aug 2023'"
    [jobDescription]="'Implemented a new Password Protection standard for a company with 12,700 employees, reducing security breaches from compromised passwords, and successfully migrated Single Sign-On (SSO) Connectors to a new Identity Provider with zero downtime, improving authentication reliability. Additionally, collaborated with an Application Security Engineer to remediate vulnerabilities in internal applications, reducing high-risk security issues and strengthening overall security posture.'">
    </app-job-card>
    <app-job-card
    [jobTitle]="'Small Group Leader'"
    [companyName]="'Willow Creek Community Church'"
    [location]="'South Barrington, IL'"
    [startDate]="'Aug 2018'"
    [endDate]="'Apr 2021'"
    [jobDescription]="'As a Small Group Leader at Willow Creek Community Church, I helped students grow in their faith through group sessions, local retreats, community volunteering, and event organization. By facilitating engaging discussions and activities, I was able to help guide them on their spiritual journeys.'">
    </app-job-card>
    <app-job-card
    [jobTitle]="'Catching Camp Instructor'"
    [companyName]="'Strikes Baseball Academy'"
    [location]="'Broadview, IL'"
    [startDate]="'Nov 2020'"
    [endDate]="'Jan 2021'"
    [jobDescription]="'Successfully served as a catching instructor for a camp, teaching catching fundamentals to 40 players in total. Utilized effective chalk talks, interactive discussions, and skill-building drills.'">
    </app-job-card>
    <a href="../assets/resume/Arista_Tyler(Fall 2024).pdf">View Full Resume &#8599;</a>
  </div>
  <div class="projects">
    <app-project-card
    [name]="'Music Translator'"
    [subtitle]="'CS336 Final Project'"
    [description]="'An ongoing project: Crafting an inventive React Native app aiming to break language barriers in music. Using Spotify and Musixmatch APIs, it will translate song lyrics.'"
    [link]="'../../../assets/musicTranslator.png'">
    </app-project-card>
    <app-project-card
    [name]="'Calvin Electronic Medical Record'"
    [subtitle]="'Senior Project'"
    [description]="'This is a web development project that utilizes NodeJS, Angular and Typescript. The goals of the upcoming year will be to enhance the application with more assessment functionalities - mother-baby, OBGYN, and pediatrics.'"
    [link]="'../../../assets/calvinEMR.png'">
    </app-project-card>
    <app-project-card
    [name]="'Baseball Analytics'"
    [subtitle]="'Personal Project'"
    [description]="'An ongoing project: Developing a mobile application that provides real-time baseball analytics, player performance metrics, & predictive sports betting insights.'"
    [link]="''">
    </app-project-card>
    <app-project-card
    [name]="'Mindful Knights'"
    [subtitle]="'CS262 Project'"
    [description]="'Developed as a project for my CS262 Software Engineering class, MindfulKnights is an app dedicated to helping students find balance amid academic stress.'"
    [link]="'../../../assets/mindfulKnight.png'">
    </app-project-card>
    <app-project-card
    [name]="'Brick Breaker'"
    [subtitle]="'CS108 Final Project'"
    [description]="'Designed and implemented a Gui-based Python application that allows the user to play a brick breaker game that implements a file-based leaderboard.'"
    [link]="'../../../assets/brickBreaker.png'">
    </app-project-card>
    <a routerLink="">View Full Project Archieve</a>
  </div>
  <footer>
    <p>Testing out footer</p>
  </footer>
</aside>

// src/app/page.tsx
'use client';

import { FaInstagram } from "react-icons/fa";
import { FaGithub } from "react-icons/fa";
import { FaLinkedin } from "react-icons/fa";
import { FaSquareXTwitter } from "react-icons/fa6";
import { IoIosMail } from "react-icons/io";
import { useRef } from 'react'

import EducationCard from "./components/EducationCard";
// import JobCard from "./components/JobCard";
import SteelcaseJobCard from "./components/SteelcaseJobCard";
import ProjectCard from "./components/ProjectCard";
// import BlogCard from "./components/BlogCard";

export default function Home() {

  const aboutRef = useRef<HTMLDivElement | null>(null);
  const educationRef = useRef<HTMLDivElement | null>(null);
  const experienceRef = useRef<HTMLDivElement | null>(null);
  const projectsRef = useRef<HTMLDivElement | null>(null);
  const blogRef = useRef<HTMLDivElement | null>(null);

  return (
    <div id="entirePage" className="grid grid-cols-2">
        <section className="ml-[15%] mr-[15%] p-[0] pt-[12%]  h-[24%] float-left box-border justify-items-center">
          <div className="intro">
            <h1 id="name" className="mt-[25px] text-[60px] text-center font-bold mb-[20px]">Tyler Arista</h1>
            <h3 className="text-center">Applications Engineer @Steelcase</h3>
          </div>
          <div className="flex flex-col mt-[20%] items-center">
            <a onClick={() => {
              aboutRef.current?.scrollIntoView(
                {behavior: "smooth"}
              );
            }}>About</a>
            <a onClick={() => {
              educationRef.current?.scrollIntoView(
                {behavior: "smooth"}
              );
            }}>Education</a>
            <a onClick={() => {
              experienceRef.current?.scrollIntoView(
                {behavior: "smooth"}
              );
            }}>Experience</a>
            <a onClick={() => {
              projectsRef.current?.scrollIntoView(
                {behavior:"smooth"}
              );
            }}>Projects</a>
            <a onClick={() => {
              blogRef.current?.scrollIntoView(
                {behavior:"smooth"}
              );
            }}>Blog</a>
          </div>
          <footer id="social" className="flex flex-row justify-center items-center mt-[45%] m-[15px] text-[30px]" style={{flex:"row"}}>
            <a href="https://github.com/tarista13" target="_blank" className="m-[15%]" style={{color:'white'}}><FaGithub/></a>
            <a href="https://www.linkedin.com/in/tyler-arista/" target="_blank" className="m-[15%]" style={{color:'white'}}><FaLinkedin/></a>
            <a href="https://www.instagram.com/t_arista13/" target="_blank" className="m-[15%]" style={{color:'white'}}><FaInstagram/></a>
            <a href="https://twitter.com/t_arista13" target="_blank" className="m-[15%]" style={{color:'white'}}><FaSquareXTwitter/></a>
            <a href="mailto:tylerarista@gmail.com" target="_blank" className="m-[15%]" style={{color:'white'}}><IoIosMail /></a>
          </footer>
      </section>
      <aside className="rounded-[5px] pl-[12%] pr-[12%] float-right h-screen box-border overflow-y-auto">
        <div ref={aboutRef} id="about" className="m-[9%]">
          {/* <p>I’m a Computer Science graduate with a Minor in Data Science from Calvin University (May 2025), 
            currently working as an Applications Engineer Associate at Steelcase. I’m passionate about full-stack development, 
            data-driven solutions, and building technology that drives meaningful impact. My long-term career goal is to grow 
            into a software engineering role, where I can apply my skills to design and deliver innovative systems that make a 
            difference. My academic background includes courses in Data Structures, Algorithms, Software Engineering, Computer 
            Architecture, Artificial Intelligence, and Machine Learning. With hands-on experience in Python, C#, JavaScript, 
            and Agile methodologies, I’m a dedicated learner and problem-solver eager to continue developing my expertise in 
            modern software development practices.</p> */}
            <p>Hi, I&#39;m Tyler, a Computer Science graduate with a minor in Data Science from Calvin University
               and currently an Applications Engineer Associate at Steelcase.<br/>
              <br/>
               I&#39;m passionate about building modern, data-driven web applications that merge clean design
               with powerful functionality. I work primarily with React, Next.js, Django, and C#, creating tools
               that are intuitive, efficient, and impactful.<br/>
              <br/>
                I enjoy tackling complex problems, learning new technologies, and collaborating with others to turn 
                ideas into real, working solutions. My goal is to continue growing into a Software Engineering role
                where I can design and deliver systems that make a meaningful difference.
            </p>
        </div>
        <div ref={educationRef} id="education" className="">
          <h2>Education</h2>
          <EducationCard
            image="/Calvin_Knights.webp"
            alt="Calvin University Logo" 
            school="Calvin University"
            major="Computer Science | Data Science"
            relevantCourses="Web Development, Database Management, AI & Machine Learning, Predictive Analytics, Applied Data Analysis, Software Engineering"></EducationCard>
        </div>
        <div ref={experienceRef} id="experience" className="mt-[5%]">
          <h2>Experience</h2>
          <SteelcaseJobCard 
              company="Steelcase"
              location="Grand Rapids, MI"
              image="/steelcaseLogo.png"
              alt="Steelcase Logo"
              title_03="Applications Engineer Associate"
              jobtype_03="Full-time"
              year_03="June 2025 - Present"
              description_03="Supporting the SAP Transportation Management(TM) system. Currently contributing to the company's Business Transformation
              initiative, migrating from SAP ECC to SAP S/4 HANA. Actively involved in design sessions defining system configurations and workflow logic, 
              while also performing ABAP development to enhance and maintain business processes."
              title_02="Software Engineer Intern"
              jobtype_02="Internship"
              year_02="May 2024 - June 2025"
              description_02="Collaborated on developing a new quoting application for customized products, improving frontend user
              experience and backend data management to streamline orders and strengthen product workflows."
              title_01="IT Security Intern"
              jobtype_01="Internship"
              year_01="May 2023 - Aug 2023"
              description_01="Implemented a new Password Protection standard for a company with 12,700 employees, reducing security breaches from
              compromised passwords. Collaborated with the AppSec engineer to review application vulnerabilities using Checkmarx."

            />
          {/* <div className="mt-[5px]">
            <JobCard
              title="Applications Enginner Associate" 
              company="Steelcase"
              image="/steelcaseLogo.png"
              alt="Steelcase Logo"
              year="June 2025 - Present" 
              description="Contributing to enterprise software and system solutions, supporting business operation, and enhacing technical
              workflows while building experience toward long-term software engineering goals."/>
          </div>
          <div className="mt-[15px]">
            <JobCard 
              title="Software Engineer Intern"
              company="Steelcase"
              alt="Steelcase Logo"
              image="/steelcaseLogo.png"
              year="May 2024 - June 2025"
              description="Collaborated on developing a new quoting application for customized products, improving frontend user
              experience and backend data management to streamline orders and strengthen product workflows."></JobCard>
          </div>
          <div className="">
            <JobCard 
              title="CyberSecurity Intern"
              company="Steelcase"
              image="/steelcaseLogo.png"
              alt="Steelcase Logo"
              year="May 2023 - Aug 2023"
              description="Implemented a new Password Protection standard for a company with 12,700 employees, reducing security breaches from
              compromised passwords. Collaborated with the AppSec engineer to review application vulnerabilities using Checkmarx."></JobCard>
          </div> */}
          <a href="./resume/Arista_Tyler(Post Grad May 2025).pdf" target="_blank" className="text-white">View Full Resume</a>
        </div>
        <div ref={projectsRef} id="projects" className="pb-[5%] mt-[5%]">
          <h1>Projects</h1>
          <div id="emr">
            <ProjectCard 
              link="https://calvin-emr.web.app/about-us"
              image="/calvinEMR.png"
              alt="Calvin EMR Project"
              title="Calvin Electronic Medical Record" 
              projectType="Senior Project" 
              techStack="Angular, TypeScript, Firebase" 
              description="This is a web development project that utilizes Angular, NodeJS and Typescript. 
              The goals of the upcoming year will be to enhance the application with more assessment 
              functionalities - mother-baby, OBGYN, and pediatrics." />
          </div>
          <div id="finance">
            <ProjectCard 
              link="https://github.com/tarista13/finance_dashboard"
              image="/financeDashboard.png"
              alt="Django Project"
              title="Personal Finance Dashboard" 
              projectType="Personal" 
              techStack="Next.js, Django, Plaid API" 
              description="A full-stack web app that helps users track spending, savings, and transactions in one place.
              Built with Django, Plaid API, and Recharts, it securely connects to bank accounts and visualizes
              income, expenses, and net worth through interactive charts." />
          </div>
          {/* <div id="baseball">
            <ProjectCard 
              link="#"
              image="/brickBreaker.png"
              alt="Baseball Project"
              title="Baseball Project" 
              projectType="Personal" 
              techStack="django" 
              description="shows off: web scraping, backend calculations, visualizations, etc" />
          </div> */}
          <div id="resume">
            <ProjectCard 
              link="https://github.com/tarista13/resume_analyzer"
              image="/resume_analyzer.png"
              alt="Resume Analyzer Django Project"
              title="AI-Powered Resume Critic" 
              projectType="Personal" 
              techStack="Next.js, Gemini API" 
              description="An AI web app that analyzes resumes and provides feedback on clarity, structure, and job relevance.
              Built with React and google Gemini, it uses NLP and prompt engineering to generate tailored suggestions that improve 
              each." />
          </div>
          <div id="brickBreaker">
            <ProjectCard 
              link="https://github.com/tarista13/Brick-Breaker"
              image="/brickBreaker.png"
              alt="Bricker Breaker Application"
              title="Brick Breaker" 
              projectType="CS108 Final Project" 
              techStack="Python" 
              description="Designed and implemented a Gui-based Python application that allows 
              the user to play a brick breaker game that implements a file-based leaderboard." />
          </div>
          <a href="">View Full Project Archieve</a>
        </div>
        {/* <div ref={blogRef} id="blog" className="">
          <h1>Blog</h1>
          <BlogCard
            title="Classifying MLB Hit Outcomes"
            description="Can we classify the outcome of a baseball hit based on the hit kinematics">
          </BlogCard>
          <BlogCard
            title="My journey as a baseball analyst -> data scientist"
            description="[...]">
          </BlogCard>
          <BlogCard
            title="2016 Cubs vs 2025 Cubs"
            description="[...]">
          </BlogCard>
          <Link href="/blog">View rest of blogs</Link>
        </div> */}
      </aside>
    </div>
  );
}
